In [1]:
import numpy as np #The Numpy numerical computing library
import pandas as pd #The Pandas data science library
import requests #The requests library for HTTP requests in Python
import xlsxwriter #The XlsxWriter libarary for 
import math #The Python math module
import pandas as pd
import json
from pandas import json_normalize

In [2]:
df_data=pd.read_excel("New option chain.xlsx",sheet_name=None)
df_data=df_data["Final"]
df_data

,PE.Symbol,PE.Date,PE.Expiry,PE.Option Type,PE.strikePrice,PE.Open,PE.High,PE.Low,PE.Close,PE.lastPrice,...,CE.Low,CE.Close,CE.lastPrice,CE.Settle Price,CE.No. of contracts,CE.Turnover in Lacs,CE.Premium Turnover in Lacs,CE.openInterest,CE.Change in OI,CE.underlyingValue
0,NIFTY,2020-11-03,2020-11-05,PE,12750,0.00,0.00,0.00,1376.60,0.00,...,0.55,1.15,1.50,1.15,701.0,6703.90,0.58,14625.0,8250.0,11813.500000
1,NIFTY,2020-11-03,2020-11-05,PE,12800,0.00,0.00,0.00,1098.05,1098.05,...,0.80,1.00,1.15,1.00,17860.0,171469.29,13.29,913350.0,-124800.0,11813.500000
2,NIFTY,2020-11-03,2020-11-05,PE,12850,0.00,0.00,0.00,1167.05,1167.05,...,0.60,1.00,1.10,1.00,183.0,1763.78,0.12,6900.0,-3375.0,11813.500000
3,NIFTY,2020-11-03,2020-11-05,PE,11800,149.55,168.55,103.05,118.75,123.00,...,90.20,132.75,139.90,132.75,434582.0,3885635.71,39585.01,1478250.0,-29175.0,11813.500000
4,NIFTY,2020-11-03,2020-11-05,PE,11850,180.00,197.55,125.55,142.30,146.00,...,63.00,105.65,113.50,105.65,182675.0,1636840.40,13316.34,369450.0,-15450.0,11813.500000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9796,NIFTY,2022-10-25,2022-10-27,PE,14200,0.40,0.40,0.15,0.20,0.15,...,0.00,2824.05,2824.05,3461.35,0.0,0.00,0.00,100.0,0.0,17656.349609
9797,NIFTY,2022-10-25,2022-10-27,PE,14150,0.45,0.55,0.10,0.30,0.50,...,0.00,2817.95,2817.95,3511.30,0.0,0.00,0.00,50.0,0.0,17656.349609
9798,NIFTY,2022-10-25,2022-10-27,PE,14100,0.40,0.45,0.10,0.20,0.15,...,0.00,3033.05,3033.05,3561.30,0.0,0.00,0.00,100.0,0.0,17656.349609
9799,NIFTY,2022-10-25,2022-10-27,PE,14050,0.40,0.45,0.15,0.15,0.15,...,0.00,3091.35,0.00,3611.30,0.0,0.00,0.00,0.0,0.0,17656.349609
9800,NIFTY,2022-10-25,2022-10-27,PE,14400,0.50,0.50,0.20,0.25,0.25,...,0.00,2570.00,2570.00,3261.40,0.0,0.00,0.00,0.0,0.0,17656.349609

In [3]:
df_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9801 entries, 0 to 9800
Data columns (total 31 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   PE.Symbol                    9801 non-null   object
 1   PE.Date                      9801 non-null   datetime64[ns]
 2   PE.Expiry                    9801 non-null   datetime64[ns]
 3   PE.Option Type               9801 non-null   object
 4   PE.strikePrice               9801 non-null   int64
 5   PE.Open                      9801 non-null   float64
 6   PE.High                      9801 non-null   float64
 7   PE.Low                       9801 non-null   float64
 8   PE.Close                     9801 non-null   float64
 9   PE.lastPrice                 9801 non-null   float64
 10  PE.Settle Price              9801 non-null   float64
 11  PE.No. of contracts          9801 non-null   int64
 12  PE.Turnover in Lacs          9801 non-null   float64
 13  PE.Premium Turnover in Lacs  9801 non-null   float64
 14  PE.openInterest              9801 non-null   int64
 15  PE.Change in OI              9801 non-null   int64
 16  PE.Underlying Value          9801 non-null   float64
 17  CE.Option Type               9726 non-null   object
 18  CE.strikePrice               9726 non-null   float64
 19  CE.Open                      9726 non-null   float64
 20  CE.High                      9726 non-null   float64
 21  CE.Low                       9726 non-null   float64
 22  CE.Close                     9726 non-null   float64
 23  CE.lastPrice                 9726 non-null   float64
 24  CE.Settle Price              9726 non-null   float64
 25  CE.No. of contracts          9726 non-null   float64
 26  CE.Turnover in Lacs          9726 non-null   float64
 27  CE.Premium Turnover in Lacs  9726 non-null   float64
 28  CE.openInterest              9726 non-null   float64
 29  CE.Change in OI              9726 non-null   float64
 30  CE.underlyingValue           9726 non-null   float64
dtypes: datetime64[ns](2), float64(22), int64(4), object(3)
memory usage: 2.3+ MB

In [5]:
df_Expiry=pd.read_excel("Expiry Date.xlsx")

         Date
0  2020-11-05
1  2020-11-12
2  2020-11-19
3  2020-11-26
4  2020-12-03
..        ...
95 2022-09-29
96 2022-10-06
97 2022-10-13
98 2022-10-20
99 2022-10-27

[100 rows x 1 columns]

In [7]:
df_data_n=df_data[df_data["PE.Expiry"]=="2020-11-05"]
df_data_n

,PE.Symbol,PE.Date,PE.Expiry,PE.Option Type,PE.strikePrice,PE.Open,PE.High,PE.Low,PE.Close,PE.lastPrice,...,CE.Low,CE.Close,CE.lastPrice,CE.Settle Price,CE.No. of contracts,CE.Turnover in Lacs,CE.Premium Turnover in Lacs,CE.openInterest,CE.Change in OI,CE.underlyingValue
0,NIFTY,2020-11-03,2020-11-05,PE,12750,0.00,0.00,0.00,1376.60,0.00,...,0.55,1.15,1.50,1.15,701.0,6703.90,0.58,14625.0,8250.0,11813.5
1,NIFTY,2020-11-03,2020-11-05,PE,12800,0.00,0.00,0.00,1098.05,1098.05,...,0.80,1.00,1.15,1.00,17860.0,171469.29,13.29,913350.0,-124800.0,11813.5
2,NIFTY,2020-11-03,2020-11-05,PE,12850,0.00,0.00,0.00,1167.05,1167.05,...,0.60,1.00,1.10,1.00,183.0,1763.78,0.12,6900.0,-3375.0,11813.5
3,NIFTY,2020-11-03,2020-11-05,PE,11800,149.55,168.55,103.05,118.75,123.00,...,90.20,132.75,139.90,132.75,434582.0,3885635.71,39585.01,1478250.0,-29175.0,11813.5
4,NIFTY,2020-11-03,2020-11-05,PE,11850,180.00,197.55,125.55,142.30,146.00,...,63.00,105.65,113.50,105.65,182675.0,1636840.40,13316.34,369450.0,-15450.0,11813.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79,NIFTY,2020-11-03,2020-11-05,PE,12250,489.10,500.00,424.50,450.00,450.00,...,5.15,9.40,11.85,9.40,32341.0,297307.74,174.80,297075.0,17250.0,11813.5
80,NIFTY,2020-11-03,2020-11-05,PE,12300,538.00,539.05,475.50,482.85,482.85,...,3.80,6.60,8.40,6.60,122837.0,1133649.71,478.39,1365300.0,-6450.0,11813.5
81,NIFTY,2020-11-03,2020-11-05,PE,11250,17.45,20.70,13.85,15.90,18.00,...,498.85,567.25,567.25,566.55,85.0,751.94,34.75,7050.0,1725.0,11813.5
82,NIFTY,2020-11-03,2020-11-05,PE,11300,13.05,31.30,13.05,18.90,21.10,...,463.90,537.00,540.10,537.00,229.0,2027.35,86.58,40500.0,-3600.0,11813.5
83,NIFTY,2020-11-03,2020-11-05,PE,11350,31.65,31.65,18.80,22.45,24.50,...,416.75,496.45,496.80,496.45,40.0,354.53,14.03,6300.0,225.0,11813.5

In [8]:
df_data_n["Difference"]=df_data_n["CE.underlyingValue"]-df_data_n["CE.strikePrice"]
df_data_n["Ratio"]=df_data_n["CE.openInterest"]/df_data_n["PE.openInterest"]

<ipython-input-8-0ce08887058e>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_data_n["Difference"]=df_data_n["CE.underlyingValue"]-df_data_n["CE.strikePrice"]
<ipython-input-8-0ce08887058e>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_data_n["Ratio"]=df_data_n["CE.openInterest"]/df_data_n["PE.openInterest"]

In [9]:
df_call=df_data_n[df_data_n["Difference"]<0].iloc[3:]
df_put=df_data_n[df_data_n["Difference"]>0].iloc[:-3]

In [10]:
df_call_1=df_call.sort_values(by=["CE.openInterest"],ascending=False).iloc[:7].sort_values(by=['Ratio'],ascending=False)
df_put_1=df_put.sort_values(by=["PE.openInterest"],ascending=False).iloc[:7].sort_values(by=['Ratio'])

In [11]:
def OverView(CE_Sell,PE_Sell,CE_Buy,PE_Buy):
    Max_Profit=round((CE_Sell+PE_Sell-CE_Buy-PE_Buy)*50,2)
    Max_Loss=round((CE_Sell+PE_Sell-CE_Buy-PE_Buy-200)*50,2)
    return [Max_Profit,Max_Loss,round(-Max_Loss/Max_Profit,2)]

In [12]:
def CallPrice(StrikePrice,Data):
    return Data[Data["CE.strikePrice"]==StrikePrice]["CE.lastPrice"].iloc[0]

def PutPrice(StrikePrice,Data):
    return Data[Data["PE.strikePrice"]==StrikePrice]["PE.lastPrice"].iloc[0]

In [17]:
my_columns = ["CE StrikePrice", 'PE StrikePrice',"CE StrikePrice 1", 'PE StrikePrice 1','Max Profit', 'Max Loss', "Risk/Reward"]
final_dataframe = pd.DataFrame(columns = my_columns)


for i in df_call_1["CE.strikePrice"]:
    l=[]
    l.append(i)
    for j in df_put_1["PE.strikePrice"]:
        l.append(j)
        l.append(l[0]+200)
        l.append(l[1]-200)
        CE_Sell=CallPrice(l[0],df_data_n)
        PE_Sell=PutPrice(l[1],df_data_n)
        CE_Buy=CallPrice(l[2],df_data_n)
        PE_Buy=PutPrice(l[3],df_data_n)
        l=l+OverView(CE_Sell,PE_Sell,CE_Buy,PE_Buy)
        final_dataframe = final_dataframe.append(
                                        pd.Series(l,index = my_columns), 
                                        ignore_index = True)
        l=[i]

<ipython-input-17-72fcb15b5edc>:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_dataframe = final_dataframe.append(
<ipython-input-17-72fcb15b5edc>:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_dataframe = final_dataframe.append(
<ipython-input-17-72fcb15b5edc>:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_dataframe = final_dataframe.append(
<ipython-input-17-72fcb15b5edc>:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_dataframe = final_dataframe.append(
<ipython-input-17-72fcb15b5edc>:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_dataframe = final_dataframe.append(
<ipython-input-17-72fcb15b5edc>:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_dataframe = final_dataframe.append(
<ipython-input-17-72fcb15b5edc>:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_dataframe = final_dataframe.append(
<ipython-input-17-72fcb15b5edc>:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_dataframe = final_dataframe.append(
<ipython-input-17-72fcb15b5edc>:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_dataframe = final_dataframe.append(
<ipython-input-17-72fcb15b5edc>:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_dataframe = final_dataframe.append(
<ipython-input-17-72fcb15b5edc>:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_dataframe = final_dataframe.append(
<ipython-input-17-72fcb15b5edc>:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_dataframe = final_dataframe.append(
<ipython-input-17-72fcb15b5edc>:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_dataframe = final_dataframe.append(
<ipython-input-17-72fcb15b5edc>:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_dataframe = final_dataframe.append(
<ipython-input-17-72fcb15b5edc>:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_dataframe = final_dataframe.append(
<ipython-input-17-72fcb15b5edc>:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_dataframe = final_dataframe.append(
<ipython-input-17-72fcb15b5edc>:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_dataframe = final_dataframe.append(
<ipython-input-17-72fcb15b5edc>:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_dataframe = final_dataframe.append(
<ipython-input-17-72fcb15b5edc>:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_dataframe = final_dataframe.append(
<ipython-input-17-72fcb15b5edc>:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_dataframe = final_dataframe.append(
<ipython-input-17-72fcb15b5edc>:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_dataframe = final_dataframe.append(
<ipython-input-17-72fcb15b5edc>:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_dataframe = final_dataframe.append(
<ipython-input-17-72fcb15b5edc>:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_dataframe = final_dataframe.append(
<ipython-input-17-72fcb15b5edc>:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_dataframe = final_dataframe.append(
<ipython-input-17-72fcb15b5edc>:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_dataframe = final_dataframe.append(
<ipython-input-17-72fcb15b5edc>:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_dataframe = final_dataframe.append(
<ipython-input-17-72fcb15b5edc>:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_dataframe = final_dataframe.append(
<ipython-input-17-72fcb15b5edc>:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_dataframe = final_dataframe.append(
<ipython-input-17-72fcb15b5edc>:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_dataframe = final_dataframe.append(
<ipython-input-17-72fcb15b5edc>:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_dataframe = final_dataframe.append(
<ipython-input-17-72fcb15b5edc>:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_dataframe = final_dataframe.append(
<ipython-input-17-72fcb15b5edc>:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_dataframe = final_dataframe.append(
<ipython-input-17-72fcb15b5edc>:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_dataframe = final_dataframe.append(
<ipython-input-17-72fcb15b5edc>:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_dataframe = final_dataframe.append(
<ipython-input-17-72fcb15b5edc>:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_dataframe = final_dataframe.append(
<ipython-input-17-72fcb15b5edc>:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_dataframe = final_dataframe.append(
<ipython-input-17-72fcb15b5edc>:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_dataframe = final_dataframe.append(
<ipython-input-17-72fcb15b5edc>:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_dataframe = final_dataframe.append(
<ipython-input-17-72fcb15b5edc>:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_dataframe = final_dataframe.append(
<ipython-input-17-72fcb15b5edc>:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_dataframe = final_dataframe.append(
<ipython-input-17-72fcb15b5edc>:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_dataframe = final_dataframe.append(
<ipython-input-17-72fcb15b5edc>:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_dataframe = final_dataframe.append(
<ipython-input-17-72fcb15b5edc>:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_dataframe = final_dataframe.append(
<ipython-input-17-72fcb15b5edc>:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_dataframe = final_dataframe.append(
<ipython-input-17-72fcb15b5edc>:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_dataframe = final_dataframe.append(
<ipython-input-17-72fcb15b5edc>:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_dataframe = final_dataframe.append(
<ipython-input-17-72fcb15b5edc>:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_dataframe = final_dataframe.append(

<ipython-input-17-72fcb15b5edc>:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_dataframe = final_dataframe.append(
<ipython-input-17-72fcb15b5edc>:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_dataframe = final_dataframe.append(

In [18]:
final_dataframe=final_dataframe[final_dataframe["Risk/Reward"]<=3]
final_dataframe

,CE StrikePrice,PE StrikePrice,CE StrikePrice 1,PE StrikePrice 1,Max Profit,Max Loss,Risk/Reward
27,12200.0,11700.0,12400.0,11500.0,2760.0,-7240.0,2.62
33,12100.0,11600.0,12300.0,11400.0,2742.5,-7257.5,2.65
34,12100.0,11700.0,12300.0,11500.0,3307.5,-6692.5,2.02
39,12000.0,11500.0,12200.0,11300.0,2942.5,-7057.5,2.4
40,12000.0,11600.0,12200.0,11400.0,3542.5,-6457.5,1.82
41,12000.0,11700.0,12200.0,11500.0,4107.5,-5892.5,1.43
42,11900.0,10700.0,12100.0,10500.0,3035.0,-6965.0,2.29
43,11900.0,10500.0,12100.0,10300.0,2947.5,-7052.5,2.39
44,11900.0,10800.0,12100.0,10600.0,3042.5,-6957.5,2.29
45,11900.0,11000.0,12100.0,10800.0,3102.5,-6897.5,2.22
46,11900.0,11500.0,12100.0,11300.0,3942.5,-6057.5,1.54
47,11900.0,11600.0,12100.0,11400.0,4542.5,-5457.5,1.2
48,11900.0,11700.0,12100.0,11500.0,5107.5,-4892.5,0.96

In [ ]:
final_dataframe["Diff"]=final_dataframe["CE StrikePrice"]-final_dataframe['PE StrikePrice']