In [1]:
import requests
import pandas as pd

In [90]:
headers={ 'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36'}
session=requests.session()
session.get("http://www1.nseindia.com", headers = headers)

In [9]:
def Volume(symbol,Time,dataType):
    url="https://www1.nseindia.com/products/dynaContent/common/productsSymbolMapping.jsp?symbol="+symbol+"&segmentLink=3&symbolCount=2&series=ALL&dateRange="+Time+"&fromDate=&toDate=&dataType="+dataType
    data = session.get(url, headers =headers)
    df=pd.read_html(data.content)[0]
    return df

In [80]:
Nifty100=pd.read_csv("ind_nifty100list.csv")

In [81]:
Nifty100

,Company Name,Industry,Symbol,Series,ISIN Code,Proper,Lower
0,ACC Ltd.,Construction Materials,ACC,EQ,INE012A01025,Acc,acc
1,Adani Enterprises Ltd.,Metals & Mining,ADANIENT,EQ,INE423A01024,Adanient,adanient
2,Adani Green Energy Ltd.,Power,ADANIGREEN,EQ,INE364U01010,Adanigreen,adanigreen
3,Adani Ports and Special Economic Zone Ltd.,Services,ADANIPORTS,EQ,INE742F01042,Adaniports,adaniports
4,Adani Total Gas Ltd.,Oil Gas & Consumable Fuels,ATGL,EQ,INE399L01023,Atgl,atgl
...,...,...,...,...,...,...,...
95,UltraTech Cement Ltd.,Construction Materials,ULTRACEMCO,EQ,INE481G01011,Ultracemco,ultracemco
96,United Spirits Ltd.,Fast Moving Consumer Goods,MCDOWELL-N,EQ,INE854D01024,Mcdowell-N,mcdowell-n
97,Vedanta Ltd.,Metals & Mining,VEDL,EQ,INE205A01025,Vedl,vedl
98,Wipro Ltd.,Information Technology,WIPRO,EQ,INE075A01022,Wipro,wipro
99,Zomato Ltd.,Consumer Services,ZOMATO,EQ,INE758T01015,Zomato,zomato

In [106]:
for i in Nifty100["Lower"]:
    headers={ 'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36'}
    session=requests.session()
    session.get("http://www1.nseindia.com", headers = headers)
    try:
        print(type(Volume(i,"1month","PRICEVOLUMEDELIVERABLE","1")),i)
    except Exception as e:
        print(type(Volume(i,"1month","PRICEVOLUMEDELIVERABLE","2")),i)

ValueError: No tables found

In [107]:
Volume("acc","1month","PRICEVOLUMEDELIVERABLE","1")

ValueError: No tables found

In [109]:
Volume("acc","1month","PRICEVOLUMEDELIVERABLE","2")

,Symbol,Series,Date,Prev Close,Open Price,High Price,Low Price,Last Price,Close Price,VWAP,Total Traded Quantity,Turnover,No. of Trades,DeliverableQty,% Dly Qt toTraded Qty
0,ACC,BL,03-Oct-2022,2254.80,2415.65,2415.65,2415.65,2415.65,2415.65,2415.65,102046,2.465074e+08,1,-,-
1,ACC,EQ,03-Oct-2022,2415.65,2419.80,2434.90,2288.00,2299.00,2301.30,2351.51,1166442,2.742904e+09,48779,393514,33.74
2,ACC,EQ,04-Oct-2022,2301.30,2355.00,2373.30,2288.05,2360.00,2359.65,2345.52,714858,1.676713e+09,35698,151688,21.22
3,ACC,EQ,06-Oct-2022,2359.65,2371.45,2397.75,2344.00,2379.00,2381.75,2378.46,690259,1.641751e+09,36234,180302,26.12
4,ACC,EQ,07-Oct-2022,2381.75,2370.15,2400.00,2350.00,2384.85,2384.75,2375.81,567262,1.347707e+09,28218,111532,19.66
5,ACC,EQ,10-Oct-2022,2384.75,2350.00,2399.90,2350.00,2375.45,2369.25,2372.27,383666,9.101604e+08,22152,51053,13.31
6,ACC,EQ,11-Oct-2022,2369.25,2375.05,2376.75,2305.70,2308.00,2311.65,2342.80,380893,8.923558e+08,21308,92002,24.15
7,ACC,EQ,12-Oct-2022,2311.65,2318.00,2339.40,2282.10,2310.00,2316.80,2309.33,611941,1.413172e+09,26880,133914,21.88
8,ACC,EQ,13-Oct-2022,2316.80,2316.00,2318.00,2242.90,2248.65,2253.90,2266.58,528138,1.197068e+09,26598,141453,26.78
9,ACC,EQ,14-Oct-2022,2253.90,2272.00,2285.95,2237.05,2238.05,2243.65,2258.63,446497,1.008470e+09,28095,103252,23.12
10,ACC,EQ,17-Oct-2022,2243.65,2232.00,2285.05,2205.30,2260.00,2270.10,2248.94,1512370,3.401236e+09,80089,309012,20.43
11,ACC,EQ,18-Oct-2022,2270.10,2259.00,2293.20,2216.00,2219.00,2219.25,2240.03,1189726,2.665022e+09,67956,339975,28.58
12,ACC,EQ,19-Oct-2022,2219.25,2219.00,2258.40,2212.55,2240.10,2246.45,2241.32,724058,1.622844e+09,38163,203685,28.13
13,ACC,EQ,20-Oct-2022,2246.45,2230.00,2299.00,2227.95,2284.95,2287.60,2267.00,713402,1.617284e+09,39341,292190,40.96
14,ACC,EQ,21-Oct-2022,2287.60,2271.00,2300.00,2241.05,2257.00,2256.55,2266.62,389554,8.829722e+08,24067,106260,31.31
15,ACC,EQ,24-Oct-2022,2256.55,2265.25,2279.85,2252.30,2256.00,2257.10,2261.50,46329,1.047731e+08,2994,13673,29.51
16,ACC,EQ,25-Oct-2022,2257.10,2260.05,2278.90,2242.80,2247.95,2247.50,2263.73,383657,8.684948e+08,18641,155896,40.63
17,ACC,EQ,27-Oct-2022,2247.50,2275.00,2318.00,2250.40,2311.00,2313.00,2290.14,561435,1.285765e+09,29211,166064,29.58
18,ACC,EQ,28-Oct-2022,2313.00,2315.00,2330.00,2284.00,2319.90,2324.45,2314.51,650727,1.506117e+09,27209,188508,41.05
19,ACC,EQ,31-Oct-2022,2324.45,2347.40,2397.90,2327.90,2390.00,2390.30,2375.51,584214,1.387809e+09,29966,184112,31.51

In [101]:
def Volume(symbol,Time,dataType,symbolCount):
    url="https://www1.nseindia.com/products/dynaContent/common/productsSymbolMapping.jsp?symbol="+symbol+"&segmentLink=3&symbolCount="+symbolCount+"&series=ALL&dateRange="+Time+"&fromDate=&toDate=&dataType="+dataType
    data = session.get(url, headers =headers)
    df=pd.read_html(data.content)[0]
    return df

In [22]:
'https://www1.nseindia.com/products/dynaContent/common/productsSymbolMapping.jsp?symbol=tcs&segmentLink=3&symbolCount=2&series=ALL&dateRange=1month&fromDate=&toDate=&dataType=PRICEVOLUMEDELIVERABLE'